"""rename_regions_to_watched_regions

Revision ID: 12935d5f34ec
Revises: 2264546da1d9
Create Date: 2025-12-01 20:34:22.804692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12935d5f34ec'
down_revision: Union[str, Sequence[str], None] = '2264546da1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_alert_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watched_regions', sa.JSON(), nullable=True))
        batch_op.drop_column('regions')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_alert_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('watched_regions')

    # ### end Alembic commands ###
