"""add_relevancy_scoring_fields

Revision ID: 12b978e4d370
Revises: 346ca0248baf
Create Date: 2025-10-27 02:18:58.776280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b978e4d370'
down_revision: Union[str, Sequence[str], None] = '346ca0248baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relevancy_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('relevancy_breakdown', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('relevancy_flags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_relevant', sa.Boolean(), nullable=False))
        batch_op.create_index(batch_op.f('ix_posts_is_relevant'), ['is_relevant'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_relevancy_score'), ['relevancy_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_relevancy_score'))
        batch_op.drop_index(batch_op.f('ix_posts_is_relevant'))
        batch_op.drop_column('is_relevant')
        batch_op.drop_column('relevancy_flags')
        batch_op.drop_column('relevancy_breakdown')
        batch_op.drop_column('relevancy_score')

    # ### end Alembic commands ###
