"""simplify_alert_preferences

Revision ID: 2264546da1d9
Revises: 90529dbdc22f
Create Date: 2025-12-01 20:20:49.218192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2264546da1d9'
down_revision: Union[str, Sequence[str], None] = '90529dbdc22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_alert_preferences', schema=None) as batch_op:
        batch_op.drop_column('alert_types')
        batch_op.drop_column('email_min_severity')
        batch_op.drop_column('disaster_types')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_alert_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disaster_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_min_severity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('alert_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
