"""add email_min_severity to user preferences

Revision ID: 346ca0248baf
Revises: e3153027d6ff
Create Date: 2025-10-26 21:35:16.547675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346ca0248baf'
down_revision: Union[str, Sequence[str], None] = 'e3153027d6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column with server default for existing rows
    with op.batch_alter_table('user_alert_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_min_severity', sa.Integer(), server_default='3', nullable=False))
    
    # Update existing rows to match their min_severity as a sensible default
    op.execute('UPDATE user_alert_preferences SET email_min_severity = min_severity WHERE email_min_severity = 3')
    
    # Remove server default after populating existing rows
    with op.batch_alter_table('user_alert_preferences', schema=None) as batch_op:
        batch_op.alter_column('email_min_severity', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_alert_preferences', schema=None) as batch_op:
        batch_op.drop_column('email_min_severity')

    # ### end Alembic commands ###
