"""add_password_field_to_users

Revision ID: 557b3a9a0b0a
Revises: 400cf6969e67
Create Date: 2025-11-11 09:05:58.884609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557b3a9a0b0a'
down_revision: Union[str, Sequence[str], None] = '400cf6969e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the index if it exists (handles both naming conventions)
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    indexes = [idx["name"] for idx in inspector.get_indexes("admin_activity_log")]

    with op.batch_alter_table('admin_activity_log', schema=None) as batch_op:
        # Try dropping with both possible names
        if "ix_admin_activity_log_created_at" in indexes:
            batch_op.drop_index("ix_admin_activity_log_created_at")
        elif "idx_admin_activity_log_created_at" in indexes:
            batch_op.drop_index("idx_admin_activity_log_created_at")

        batch_op.create_index(batch_op.f('ix_admin_activity_log_id'), ['id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    connection = op.get_bind()
    inspector = sa.inspect(connection)
    indexes = [idx["name"] for idx in inspector.get_indexes("admin_activity_log")]

    with op.batch_alter_table('admin_activity_log', schema=None) as batch_op:
        if "ix_admin_activity_log_id" in indexes:
            batch_op.drop_index(batch_op.f("ix_admin_activity_log_id"))

        # Recreate with the original naming convention
        if (
            "idx_admin_activity_log_created_at" not in indexes
            and "ix_admin_activity_log_created_at" not in indexes
        ):
            batch_op.create_index(
                "idx_admin_activity_log_created_at", ["created_at"], unique=False
            )

    # ### end Alembic commands ###
