"""add comprehensive logging tables

Revision ID: 5d72963c4bf1
Revises: 12b978e4d370
Create Date: 2025-11-03 18:47:07.021678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d72963c4bf1'
down_revision: Union[str, Sequence[str], None] = '12b978e4d370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_exceeded', sa.Boolean(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('memory_mb', sa.Float(), nullable=True),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_logs', schema=None) as batch_op:
        batch_op.create_index('idx_perf_logs_exceeded', ['is_exceeded'], unique=False, postgresql_where='is_exceeded = true')
        batch_op.create_index(batch_op.f('ix_performance_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performance_logs_metric_type'), ['metric_type'], unique=False)

    op.create_table('api_request_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('request_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('db_queries_count', sa.Integer(), nullable=True),
    sa.Column('db_query_time_ms', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.create_index('idx_api_logs_slow', ['duration_ms'], unique=False, postgresql_where='duration_ms > 1000')
        batch_op.create_index(batch_op.f('ix_api_request_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_request_logs_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_request_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_request_logs_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_request_logs_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_admin_action', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('error_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_function', sa.String(length=100), nullable=True),
    sa.Column('source_line', sa.Integer(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_occurred_at', sa.DateTime(), nullable=False),
    sa.Column('last_occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_last_occurred_at'), ['last_occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_user_id'), ['user_id'], unique=False)

    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('log_category', sa.String(length=50), nullable=False),
    sa.Column('log_level', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index('idx_system_logs_composite', ['log_category', 'created_at', 'user_id'], unique=False)
        batch_op.create_index('idx_system_logs_details', ['details'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_system_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_log_category'), ['log_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_log_level'), ['log_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_system_logs_log_level'))
        batch_op.drop_index(batch_op.f('ix_system_logs_log_category'))
        batch_op.drop_index(batch_op.f('ix_system_logs_id'))
        batch_op.drop_index(batch_op.f('ix_system_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_system_logs_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_system_logs_action'))
        batch_op.drop_index('idx_system_logs_details', postgresql_using='gin')
        batch_op.drop_index('idx_system_logs_composite')

    op.drop_table('system_logs')
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_error_logs_severity'))
        batch_op.drop_index(batch_op.f('ix_error_logs_last_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_error_logs_is_resolved'))
        batch_op.drop_index(batch_op.f('ix_error_logs_id'))
        batch_op.drop_index(batch_op.f('ix_error_logs_error_type'))

    op.drop_table('error_logs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_audit_logs_resource')

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_request_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_request_logs_status_code'))
        batch_op.drop_index(batch_op.f('ix_api_request_logs_id'))
        batch_op.drop_index(batch_op.f('ix_api_request_logs_endpoint'))
        batch_op.drop_index(batch_op.f('ix_api_request_logs_created_at'))
        batch_op.drop_index('idx_api_logs_slow', postgresql_where='duration_ms > 1000')

    op.drop_table('api_request_logs')
    with op.batch_alter_table('performance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_logs_metric_type'))
        batch_op.drop_index(batch_op.f('ix_performance_logs_id'))
        batch_op.drop_index(batch_op.f('ix_performance_logs_created_at'))
        batch_op.drop_index('idx_perf_logs_exceeded', postgresql_where='is_exceeded = true')

    op.drop_table('performance_logs')
    # ### end Alembic commands ###
