"""add user map preferences

Revision ID: 90529dbdc22f
Revises: e72e335c26c5
Create Date: 2025-11-12 20:41:03.702622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90529dbdc22f'
down_revision: Union[str, Sequence[str], None] = 'e72e335c26c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_map_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('light_style', sa.String(length=100), nullable=False),
    sa.Column('dark_style', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_map_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_map_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_map_preferences_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_map_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_map_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_map_preferences_id'))

    op.drop_table('user_map_preferences')
    # ### end Alembic commands ###
