"""add onboarding_completed to users

Revision ID: a49bba7e2636
Revises: 12935d5f34ec
Create Date: 2025-12-09 03:52:52.537321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49bba7e2636'
down_revision: Union[str, Sequence[str], None] = '12935d5f34ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    
    # Set existing users with location to True (they completed onboarding)
    # Set existing users without location to False (they need to complete onboarding)
    op.execute("UPDATE users SET onboarding_completed = CASE WHEN location IS NOT NULL THEN TRUE ELSE FALSE END")
    
    # Now make the column non-nullable with a default
    op.alter_column('users', 'onboarding_completed', nullable=False, server_default=sa.text('false'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')

    # ### end Alembic commands ###
