import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Img,
  Link,
  Preview,
  Section,
  Text,
  Hr,
} from '@react-email/components';
import * as React from 'react';

interface Crisis {
  type: string;
  location: string;
  date: string;
  severity?: string;
}

interface WeeklyDigestProps {
  userName: string;
  weekStart: string;
  weekEnd: string;
  crisisCount: number;
  crises: Crisis[];
  logoUrl?: string;
  dashboardUrl?: string;
}

export const WeeklyDigestTemplate = ({
  userName = 'User',
  weekStart = '2024-01-01',
  weekEnd = '2024-01-07',
  crisisCount = 0,
  crises = [],
  logoUrl = 'https://bluerelief.com/logo.png',
  dashboardUrl = 'https://bluerelief.com/dashboard',
}: WeeklyDigestProps) => {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  };

  const getSeverityColor = (severity?: string) => {
    switch (severity?.toLowerCase()) {
      case 'critical': return '#dc3545';
      case 'high': return '#fd7e14';
      case 'medium': return '#ffc107';
      case 'low': return '#28a745';
      default: return '#6c757d';
    }
  };

  return (
    <Html>
      <Head />
      <Preview>Weekly Crisis Digest for {userName} - {String(crisisCount)} incidents reported</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={logoContainer}>
            <Img
              src={logoUrl}
              width="120"
              height="40"
              alt="BlueRelief"
              style={logo}
            />
          </Section>
          
          <Section style={headerSection}>
            <Heading style={titleText}>Weekly Crisis Digest</Heading>
            <Text style={subtitleText}>
              {formatDate(weekStart)} - {formatDate(weekEnd)}
            </Text>
            <Text style={greetingText}>Hello {userName},</Text>
          </Section>
          
          <Section style={summarySection}>
            <Text style={summaryTitle}>📊 This Week's Summary</Text>
            <Text style={crisisCountText}>
              <strong>{crisisCount}</strong> crisis incidents reported
            </Text>
            {crisisCount > 0 && (
              <Text style={summarySubtext}>
                Stay informed about the latest developments in your area.
              </Text>
            )}
          </Section>
          
          {crises.length > 0 && (
            <Section style={crisesSection}>
              <Text style={crisesTitle}>🚨 Recent Incidents</Text>
              {crises.slice(0, 5).map((crisis, index) => (
                <Section key={index} style={crisisItem}>
                  <Text style={crisisType}>{crisis.type}</Text>
                  <Text style={crisisLocation}>📍 {crisis.location}</Text>
                  <Text style={crisisDate}>📅 {formatDate(crisis.date)}</Text>
                  {crisis.severity && (
                    <Text style={{
                      ...severityTag,
                      color: getSeverityColor(crisis.severity)
                    }}>
                      {crisis.severity.toUpperCase()}
                    </Text>
                  )}
                </Section>
              ))}
              {crises.length > 5 && (
                <Text style={moreText}>
                  ... and {crises.length - 5} more incidents
                </Text>
              )}
            </Section>
          )}
          
          <Section style={actionSection}>
            <Link style={dashboardButton} href={dashboardUrl}>
              View Full Dashboard
            </Link>
          </Section>
          
          <Hr style={divider} />
          
          <Section style={footerSection}>
            <Text style={footerText}>
              This weekly digest is automatically generated by BlueRelief.
            </Text>
            <Text style={footerText}>
              <Link href="https://bluerelief.com/settings" style={linkText}>
                Manage your notification preferences
              </Link>
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

// Styles
const main = {
  backgroundColor: '#f6f9fc',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '20px 0 48px',
  marginBottom: '64px',
  borderRadius: '8px',
  boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
};

const logoContainer = {
  padding: '32px 20px 20px',
  textAlign: 'center' as const,
};

const logo = {
  margin: '0 auto',
};

const headerSection = {
  textAlign: 'center' as const,
  padding: '20px',
};

const titleText = {
  color: '#333',
  fontSize: '28px',
  fontWeight: 'bold',
  margin: '0 0 8px 0',
  textAlign: 'center' as const,
};

const subtitleText = {
  color: '#666',
  fontSize: '16px',
  margin: '0 0 16px 0',
};

const greetingText = {
  color: '#333',
  fontSize: '18px',
  margin: '0 0 24px 0',
};

const summarySection = {
  padding: '20px',
  backgroundColor: '#f8f9fa',
  borderRadius: '8px',
  margin: '0 20px 24px',
};

const summaryTitle = {
  color: '#333',
  fontSize: '20px',
  fontWeight: 'bold',
  margin: '0 0 16px 0',
};

const crisisCountText = {
  color: '#333',
  fontSize: '24px',
  margin: '0 0 8px 0',
};

const summarySubtext = {
  color: '#666',
  fontSize: '14px',
  margin: '0',
};

const crisesSection = {
  padding: '0 20px 24px',
};

const crisesTitle = {
  color: '#333',
  fontSize: '20px',
  fontWeight: 'bold',
  margin: '0 0 16px 0',
};

const crisisItem = {
  backgroundColor: '#ffffff',
  border: '1px solid #e9ecef',
  borderRadius: '6px',
  padding: '16px',
  margin: '0 0 12px 0',
};

const crisisType = {
  color: '#333',
  fontSize: '16px',
  fontWeight: 'bold',
  margin: '0 0 8px 0',
};

const crisisLocation = {
  color: '#666',
  fontSize: '14px',
  margin: '0 0 4px 0',
};

const crisisDate = {
  color: '#666',
  fontSize: '14px',
  margin: '0 0 8px 0',
};

const severityTag = {
  display: 'inline-block',
  fontSize: '12px',
  fontWeight: 'bold',
  padding: '4px 8px',
  borderRadius: '4px',
  backgroundColor: '#f8f9fa',
  border: '1px solid currentColor',
};

const moreText = {
  color: '#666',
  fontSize: '14px',
  fontStyle: 'italic' as const,
  textAlign: 'center' as const,
  margin: '16px 0 0',
};

const actionSection = {
  textAlign: 'center' as const,
  margin: '32px 0',
  padding: '0 20px',
};

const dashboardButton = {
  backgroundColor: '#007ee6',
  borderRadius: '6px',
  color: '#fff',
  fontSize: '16px',
  fontWeight: 'bold',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '14px 28px',
  boxShadow: '0 2px 4px rgba(0, 126, 230, 0.3)',
};

const divider = {
  borderColor: '#e9ecef',
  margin: '32px 0 24px',
};

const footerSection = {
  padding: '0 20px',
  textAlign: 'center' as const,
};

const footerText = {
  color: '#6c757d',
  fontSize: '12px',
  lineHeight: '16px',
  margin: '8px 0',
};

const linkText = {
  color: '#007ee6',
  textDecoration: 'none',
};

export default WeeklyDigestTemplate;
