import {
  Body,
  Container,
  Head,
  Heading,
  Html,
  Link,
  Preview,
  Section,
  Text,
  Hr,
} from '@react-email/components';
import * as React from 'react';

interface Crisis {
  type: string;
  location: string;
  date: string;
  severity?: string;
}

interface WeeklyDigestProps {
  userName: string;
  weekStart: string;
  weekEnd: string;
  crisisCount: number;
  crises: Crisis[];
  dashboardUrl?: string;
}

const Logo = () => (
  <svg
    width="48"
    height="48"
    viewBox="0 0 100 100"
    style={{ margin: '0 auto', display: 'block' }}
  >
    <defs>
      <mask id="logo-mask">
        <rect x="0" y="0" width="100" height="100" rx="20" ry="20" fill="white" />
        <rect x="25" y="25" width="50" height="50" rx="8" ry="8" fill="black" />
      </mask>
    </defs>
    <rect
      x="0"
      y="0"
      width="100"
      height="100"
      rx="20"
      ry="20"
      fill="#196EE3"
      mask="url(#logo-mask)"
    />
  </svg>
);

export const WeeklyDigestTemplate = ({
  userName = 'User',
  weekStart = '2024-01-01',
  weekEnd = '2024-01-07',
  crisisCount = 0,
  crises = [],
  dashboardUrl = 'https://bluerelief.com/dashboard',
}: WeeklyDigestProps) => {
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  };

  const getSeverityConfig = (severity?: string) => {
    const configs = {
      'critical': { color: '#ef4444', bg: '#fee2e2' },
      'high': { color: '#f97316', bg: '#ffedd5' },
      'medium': { color: '#f59e0b', bg: '#fef3c7' },
      'low': { color: '#22c55e', bg: '#dcfce7' },
    };
    return configs[severity?.toLowerCase() as keyof typeof configs] || { color: '#64748b', bg: '#f1f5f9' };
  };

  return (
    <Html>
      <Head />
      <Preview>Weekly Crisis Digest for {userName} - {String(crisisCount)} incidents reported</Preview>
      <Body style={main}>
        <Container style={container}>
          <Section style={logoContainer}>
            <Logo />
          </Section>
          
          <Section style={headerSection}>
            <Heading style={titleText}>Weekly Crisis Digest</Heading>
            <Text style={subtitleText}>
              {formatDate(weekStart)} - {formatDate(weekEnd)}
            </Text>
            <Text style={greetingText}>Hello {userName},</Text>
          </Section>
          
          <Section style={summarySection}>
            <Section style={summaryCard}>
              <Text style={summaryIcon}>📊</Text>
              <Text style={summaryTitle}>This Week's Summary</Text>
              <Text style={crisisCountText}>
                <span style={countNumber}>{crisisCount}</span> crisis incidents reported
              </Text>
              {crisisCount > 0 && (
                <Text style={summarySubtext}>
                  Stay informed about the latest developments in your area.
                </Text>
              )}
            </Section>
          </Section>
          
          {crises.length > 0 && (
            <Section style={crisesSection}>
              <Text style={crisesTitle}>🚨 Recent Incidents</Text>
              {crises.slice(0, 5).map((crisis, index) => (
                <Section key={index} style={crisisItem}>
                  <Section style={crisisHeader}>
                    <Text style={crisisType}>{crisis.type}</Text>
                    {crisis.severity && (
                      <Text style={{
                        ...severityTag,
                        backgroundColor: getSeverityConfig(crisis.severity).bg,
                        color: getSeverityConfig(crisis.severity).color,
                      }}>
                        {crisis.severity.toUpperCase()}
                      </Text>
                    )}
                  </Section>
                  <Text style={crisisLocation}>📍 {crisis.location}</Text>
                  <Text style={crisisDate}>📅 {formatDate(crisis.date)}</Text>
                </Section>
              ))}
              {crises.length > 5 && (
                <Section style={moreBox}>
                  <Text style={moreText}>
                    + {crises.length - 5} more incidents this week
                  </Text>
                </Section>
              )}
            </Section>
          )}
          
          <Section style={actionSection}>
            <Link style={dashboardButton} href={dashboardUrl}>
              View Full Dashboard
            </Link>
          </Section>
          
          <Hr style={divider} />
          
          <Section style={footerSection}>
            <Text style={footerText}>
              This weekly digest is automatically generated by BlueRelief.
            </Text>
            <Text style={footerText}>
              <Link href="https://bluerelief.com/settings" style={linkText}>
                Manage your notification preferences
              </Link>
            </Text>
          </Section>
        </Container>
      </Body>
    </Html>
  );
};

const main = {
  backgroundColor: '#f8fafc',
  fontFamily: 'Lato, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
};

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '40px 20px',
  maxWidth: '600px',
  borderRadius: '8px',
  boxShadow: '0 2px 8px rgba(0, 0, 0, 0.05)',
};

const logoContainer = {
  padding: '0 0 24px',
  textAlign: 'center' as const,
};

const headerSection = {
  textAlign: 'center' as const,
  padding: '0 0 24px',
};

const titleText = {
  color: '#020617',
  fontSize: '28px',
  fontWeight: '700',
  margin: '0 0 8px',
  lineHeight: '1.2',
};

const subtitleText = {
  color: '#475569',
  fontSize: '16px',
  margin: '0 0 16px',
  fontWeight: '500',
};

const greetingText = {
  color: '#334155',
  fontSize: '16px',
  margin: '0',
};

const summarySection = {
  padding: '0 0 32px',
};

const summaryCard = {
  background: 'linear-gradient(135deg, #eef2ff 0%, #e0e7ff 100%)',
  borderRadius: '8px',
  padding: '24px',
  textAlign: 'center' as const,
  border: '1px solid #c7d2fe',
};

const summaryIcon = {
  fontSize: '32px',
  margin: '0 0 12px',
  lineHeight: '1',
};

const summaryTitle = {
  color: '#020617',
  fontSize: '18px',
  fontWeight: '600',
  margin: '0 0 16px',
};

const crisisCountText = {
  color: '#334155',
  fontSize: '20px',
  margin: '0 0 8px',
  lineHeight: '1.4',
};

const countNumber = {
  color: '#196EE3',
  fontSize: '32px',
  fontWeight: '700',
  display: 'inline-block',
};

const summarySubtext = {
  color: '#475569',
  fontSize: '14px',
  margin: '0',
};

const crisesSection = {
  padding: '0 0 24px',
};

const crisesTitle = {
  color: '#020617',
  fontSize: '20px',
  fontWeight: '700',
  margin: '0 0 16px',
};

const crisisItem = {
  backgroundColor: '#f8fafc',
  border: '1px solid #e2e8f0',
  borderRadius: '8px',
  padding: '16px',
  margin: '0 0 12px',
};

const crisisHeader = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  margin: '0 0 12px',
};

const crisisType = {
  color: '#020617',
  fontSize: '16px',
  fontWeight: '600',
  margin: '0',
  lineHeight: '1.4',
};

const severityTag = {
  display: 'inline-block',
  fontSize: '11px',
  fontWeight: '600',
  padding: '4px 10px',
  borderRadius: '12px',
  letterSpacing: '0.5px',
  lineHeight: '1',
};

const crisisLocation = {
  color: '#475569',
  fontSize: '14px',
  margin: '0 0 4px',
  lineHeight: '1.4',
};

const crisisDate = {
  color: '#64748b',
  fontSize: '13px',
  margin: '0',
  lineHeight: '1.4',
};

const moreBox = {
  backgroundColor: '#f8fafc',
  border: '1px dashed #cbd5e1',
  borderRadius: '8px',
  padding: '16px',
  textAlign: 'center' as const,
};

const moreText = {
  color: '#64748b',
  fontSize: '14px',
  fontWeight: '500',
  margin: '0',
};

const actionSection = {
  textAlign: 'center' as const,
  margin: '32px 0',
};

const dashboardButton = {
  backgroundColor: '#196EE3',
  borderRadius: '8px',
  color: '#ffffff',
  fontSize: '16px',
  fontWeight: '600',
  textDecoration: 'none',
  textAlign: 'center' as const,
  display: 'inline-block',
  padding: '14px 32px',
  boxShadow: '0 2px 4px rgba(25, 110, 227, 0.25)',
};

const divider = {
  borderColor: '#e2e8f0',
  margin: '32px 0',
};

const footerSection = {
  textAlign: 'center' as const,
};

const footerText = {
  color: '#64748b',
  fontSize: '12px',
  lineHeight: '1.5',
  margin: '0 0 8px',
};

const linkText = {
  color: '#196EE3',
  textDecoration: 'none',
};

export default WeeklyDigestTemplate;
