name: Auto Merge

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
  workflow_run:
    workflows: ["Deploy Preview"]
    types: [completed]
  pull_request:
    types: [synchronize]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' || 
      github.event.pull_request.draft == false &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    steps:
      - name: Check if PR is ready for auto-merge
        id: check-ready
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let prNumber;
            
            if (context.payload.pull_request) {
              prNumber = context.payload.pull_request.number;
            } else if (context.payload.workflow_run) {
              const workflowRun = context.payload.workflow_run;
              const prs = workflowRun.pull_requests;
              if (prs && prs.length > 0) {
                prNumber = prs[0].number;
              } else {
                console.log('No PR associated with this workflow run');
                return false;
              }
            } else {
              console.log('Could not determine PR number from context');
              return false;
            }
            
            console.log(`Processing PR #${prNumber}`);
            console.log(`Event type: ${context.eventName}`);
            console.log(`Workflow run ID: ${context.runId}`);
            
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            
            const approvedReviews = reviews.filter(review => review.state === 'APPROVED');
            const hasApproval = approvedReviews.length > 0;
            console.log(`Approved reviews: ${approvedReviews.length}`);
            
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            
            if (pr.draft) {
              console.log('PR is a draft, skipping auto-merge');
              return false;
            }
            
            if (pr.user.login === 'dependabot[bot]') {
              console.log('PR is from dependabot, skipping auto-merge');
              return false;
            }
            
            console.log(`PR mergeable: ${pr.mergeable}`);
            console.log(`PR mergeable_state: ${pr.mergeable_state}`);
            
            const { data: checkRuns } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha,
            });
            
            const { data: statuses } = await github.rest.repos.getCombinedStatusForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha,
            });
            
            const { data: workflowRuns } = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: pr.head.sha,
              per_page: 100
            });
            
            const previewWorkflow = workflowRuns.workflow_runs.find(
              run => run.name === 'Deploy Preview' && run.head_sha === pr.head.sha
            );
            
            const previewComplete = !previewWorkflow || previewWorkflow.status === 'completed';
            const previewSuccess = !previewWorkflow || previewWorkflow.conclusion === 'success';
            
            console.log(`Preview workflow found: ${!!previewWorkflow}`);
            if (previewWorkflow) {
              console.log(`Preview workflow status: ${previewWorkflow.status}`);
              console.log(`Preview workflow conclusion: ${previewWorkflow.conclusion}`);
            }
            
            const relevantChecks = checkRuns.check_runs.filter(
              run => run.name !== 'enable-auto-merge'
            );
            
            const allChecksComplete = relevantChecks.length === 0 || relevantChecks.every(
              run => run.status === 'completed'
            );
            const allChecksPassed = relevantChecks.length === 0 || relevantChecks.every(
              run => run.conclusion === 'success' || run.conclusion === 'skipped' || run.conclusion === 'neutral'
            );
            
            const statusesOk = statuses.state === 'success' || statuses.statuses.length === 0;
            
            console.log(`Total check runs: ${checkRuns.check_runs.length}`);
            console.log(`Relevant checks: ${relevantChecks.length}`);
            console.log(`All checks complete: ${allChecksComplete}`);
            console.log(`All checks passed: ${allChecksPassed}`);
            console.log(`Commit statuses state: ${statuses.state}`);
            console.log(`Commit statuses count: ${statuses.statuses.length}`);
            console.log(`Statuses OK: ${statusesOk}`);
            console.log(`Preview complete: ${previewComplete}`);
            console.log(`Preview success: ${previewSuccess}`);
            
            const isReady = hasApproval && allChecksComplete && allChecksPassed && statusesOk && previewComplete && previewSuccess;
            console.log(`PR ready for auto-merge: ${isReady}`);
            
            if (!isReady) {
              console.log('Waiting for:');
              if (!hasApproval) console.log('  - Approval');
              if (!allChecksComplete) console.log('  - Checks to complete');
              if (!allChecksPassed) console.log('  - Checks to pass');
              if (!statusesOk) console.log('  - Commit statuses to succeed');
              if (!previewComplete) console.log('  - Preview deployment to complete');
              if (!previewSuccess) console.log('  - Preview deployment to succeed');
            }
            
            return isReady;

      - name: Enable auto-merge
        if: steps.check-ready.outputs.result == 'true'
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              let prNumber;
              
              if (context.payload.pull_request) {
                prNumber = context.payload.pull_request.number;
              } else if (context.payload.workflow_run) {
                const prs = context.payload.workflow_run.pull_requests;
                if (prs && prs.length > 0) {
                  prNumber = prs[0].number;
                }
              }
              
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              });
              
              const pullRequestId = pr.node_id;
              
              const mutation = `
                mutation($pullRequestId: ID!, $mergeMethod: PullRequestMergeMethod!) {
                  enablePullRequestAutoMerge(input: {
                    pullRequestId: $pullRequestId,
                    mergeMethod: $mergeMethod
                  }) {
                    pullRequest {
                      autoMergeRequest {
                        enabledAt
                        enabledBy {
                          login
                        }
                      }
                    }
                  }
                }
              `;
              
              const result = await github.graphql(mutation, {
                pullRequestId: pullRequestId,
                mergeMethod: 'MERGE'
              });
              
              console.log('✅ Auto-merge enabled successfully');
              console.log(result);
            } catch (error) {
              if (error.message.includes('already enabled') || error.message.includes('auto-merge is already enabled')) {
                console.log('ℹ️  Auto-merge already enabled');
              } else if (error.message.includes('unstable status')) {
                console.log('⏳ PR is not ready yet - checks may still be running or branch protection rules not met');
                console.log('This workflow will retry when the check_suite completes');
              } else {
                console.error('❌ Error enabling auto-merge:', error.message);
                throw error;
              }
            }

      - name: Add comment
        if: steps.check-ready.outputs.result == 'true'
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let prNumber;
            
            if (context.payload.pull_request) {
              prNumber = context.payload.pull_request.number;
            } else if (context.payload.workflow_run) {
              const prs = context.payload.workflow_run.pull_requests;
              if (prs && prs.length > 0) {
                prNumber = prs[0].number;
              }
            }
            
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('Auto-merge enabled')
            );
            
            if (!botComment) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: '✅ **Auto-merge enabled** - This PR will be automatically merged when all checks pass.'
              });
            }